In [9]:
iris<-read.csv("http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",header = F)

colnames(iris)<-c("sepal_length","sepal_width","petal_length","petal_width","cls")


head(iris)

sepal_length sepal_width petal_length petal_width cls        
1 5.1          3.5         1.4          0.2         Iris-setosa
2 4.9          3.0         1.4          0.2         Iris-setosa
3 4.7          3.2         1.3          0.2         Iris-setosa
4 4.6          3.1         1.5          0.2         Iris-setosa
5 5.0          3.6         1.4          0.2         Iris-setosa
6 5.4          3.9         1.7          0.4         Iris-setosa

In [10]:
myPCA<- function(df){
    
    eig<- eigen(cov(df))
    means<-unlist(lapply(df,mean))
    scores<- scale(df,center = means) %*% eig$vectors
    list(values=eig$values,vectors=eig$vectors,scores=scores)
}

In [11]:
my_pca<- myPCA(iris[1:4])

head(my_pca)

$values
[1] 4.22484077 0.24224357 0.07852391 0.02368303

$vectors
            [,1]        [,2]        [,3]       [,4]
[1,]  0.36158968  0.65653988 -0.58099728  0.3172545
[2,] -0.08226889  0.72971237  0.59641809 -0.3240944
[3,]  0.85657211 -0.17576740  0.07252408 -0.4797190
[4,]  0.35884393 -0.07470647  0.54906091  0.7511206

$scores
              [,1]         [,2]        [,3]         [,4]
  [1,] -2.02385337  0.493956837  0.31958154 -0.959783725
  [2,] -2.01631839 -0.506084044 -0.22785267 -0.662679198
  [3,] -2.19014626 -0.318106515  0.18346747 -0.861608114
  [4,] -2.11774544 -0.585609774  0.12429925 -0.879551780
  [5,] -2.08649383  0.582964720  0.52729679 -1.072842420
  [6,] -1.72906556  1.355526369  0.81552287 -1.028550326
  [7,] -2.17619273 -0.080555678  0.60479083 -0.978178944
  [8,] -1.99999949  0.236415342  0.25630295 -0.950538918
  [9,] -2.21567851 -1.070807472 -0.01458902 -0.779496744
 [10,] -2.03376591 -0.337962914 -0.15813585 -0.863035987
 [11,] -1.88225354  1.058440459  0.38830666 -1.021526055
 [12,] -2.03878608  0.067881729  0.40073961 -1.054352805
 [13,] -2.10700591 -0.575580881 -0.22963516 -0.799414232
 [14,] -2.47098054 -0.942125209  0.10884950 -0.909412343
 [15,] -1.91014841  1.910350868  0.50797927 -1.010947771
 [16,] -1.79002766  2.454776703  1.28457320 -1.232965198
 [17,] -1.92325332  1.395373426  0.79908142 -0.919796430
 [18,] -1.97683262  0.484167750  0.39152718 -0.861361398
 [19,] -1.62611232  1.434879422  0.39553568 -0.937288544
 [20,] -1.98520678  0.979087405  0.80829385 -1.112787837
 [21,] -1.72823856  0.533635511 -0.01612892 -0.851665039
 [22,] -1.91921233  0.801004512  0.74268739 -0.939619522
 [23,] -2.45534864  0.305668080  0.79150794 -1.117339351
 [24,] -1.69920289  0.098116670  0.27264536 -0.596590190
 [25,] -1.89314526  0.037996436  0.41307070 -1.135918227
 [26,] -1.87555775 -0.446721648 -0.28979509 -0.678743439
 [27,] -1.85741105  0.206875404  0.40430460 -0.780882738
 [28,] -1.93163967  0.563280997  0.25352875 -0.948659492
 [29,] -1.96121291  0.404948955  0.11186629 -0.846725030
 [30,] -2.04450544 -0.347991808  0.19579856 -0.943173536
 [31,] -1.98186498 -0.436999690 -0.01191669 -0.830114841
 [32,] -1.73129093  0.533980865  0.11954164 -0.600443437
 [33,] -2.09250263  1.582832923  1.00689572 -1.495557748
 [34,] -1.98200223  1.989157180  1.00179365 -1.329754815
 [35,] -2.03376591 -0.337962914 -0.15813585 -0.863035987
 [36,] -2.10769291 -0.070286978 -0.03113234 -0.719481520
 [37,] -1.89773326  0.821062299  0.03481858 -0.779344424
 [38,] -2.03376591 -0.337962914 -0.15813585 -0.863035987
 [39,] -2.28319915 -0.892551901  0.11885272 -0.827054258
 [40,] -1.95633273  0.315701267  0.18613980 -0.912226211
 [41,] -2.06904632  0.414843590  0.45757997 -0.872485631
 [42,] -2.05969572 -2.001111709 -0.84222950 -0.167097307
 [43,] -2.32114655 -0.555964288  0.39395692 -0.976546234
 [44,] -1.78234324  0.355591036  0.68574799 -0.658784072
 [45,] -1.74399827  0.929451261  0.89668095 -1.123119406
 [46,] -2.01296440 -0.595159055 -0.08574387 -0.602569578
 [47,] -1.98368060  0.978914728  0.74045857 -1.238398638
 [48,] -2.18526608 -0.407354204  0.25774098 -0.927109295
 [49,] -1.92592031  0.979154535  0.45846981 -1.059838762
 [50,] -2.02957273  0.078083300  0.11464049 -0.848604456
 [51,]  1.02903426  1.049300712 -0.42718492  0.276243948
 [52,]  0.71696056  0.583719607  0.05751889  0.199166983
 [53,]  1.14845583  0.772008365 -0.41440751  0.356722608
 [54,]  0.15794680 -1.575110974 -0.71342477  0.466164231
 [55,]  0.88506906 -0.020131459 -0.55874230  0.509275168
 [56,]  0.39314651 -0.624878914 -0.14543875  0.033117334
 [57,]  0.79843472  0.643014874  0.34540052  0.130153667
 [58,] -0.60391832 -1.783433102 -0.39950324  0.056594340
 [59,]  0.81572062  0.247026447 -0.63524464  0.275997233
 [60,] -0.05047449 -1.139620844  0.11510837  0.177852960
 [61,] -0.38726287 -2.397245932 -1.01165407  0.339514051
 [62,]  0.39093332 -0.119412334  0.12089935  0.238660847
 [63,]  0.25419206 -1.317607897 -1.41762955  0.437206772
 [64,]  0.6929544

In [8]:
pca <- princomp(iris[1:4],scores = T)
cbind(unlist(lapply(my_pca[1],sqrt)),pca$sdev)

[,1]      [,2]     
values1 2.0504602 2.0435679
values2 0.4930982 0.4914407
values3 0.2811606 0.2802155
values4 0.1544119 0.1538929

In [12]:
summary(pca)

Importance of components:
                          Comp.1     Comp.2     Comp.3      Comp.4
Standard deviation     2.0435679 0.49144068 0.28021551 0.153892885
Proportion of Variance 0.9239544 0.05343362 0.01737228 0.005239737
Cumulative Proportion  0.9239544 0.97738799 0.99476026 1.000000000

In [13]:
my_pca[[1]] / sum(my_pca[[1]])

[1] 0.924616207 0.053015568 0.017185140 0.005183085