In [1]:
%pylab inline
%load_ext rmagic

/usr/local/lib/python2.7/dist-packages/rpy2-2.8.2-py2.7-linux-x86_64.egg/rpy2/rinterface/__init__.py:185: RRuntimeWarning: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib64/R/library/stats/libs/stats.so':
  libRlapack.so: cannot open shared object file: No such file or directory

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python2.7/dist-packages/rpy2-2.8.2-py2.7-linux-x86_64.egg/rpy2/rinterface/__init__.py:185: RRuntimeWarning: During startup - 
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python2.7/dist-packages/rpy2-2.8.2-py2.7-linux-x86_64.egg/rpy2/rinterface/__init__.py:185: RRuntimeWarning: Warning message:

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python2.7/dist-packages/rpy2-2.8.2-py2.7-linux-x86_64.egg/rpy2/rinterface/__init__.py:185: RRuntimeWarning: package ‘stats’ in options("defaultPackages") was not found 

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python2.7/dist-packages/IPython/extensions/

Populating the interactive namespace from numpy and matplotlib


In [2]:
%%R
# pause after each graph
par(ask = TRUE)

# --Section 3.1--

attach(mtcars)
mtcars


                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0   

In [3]:
%%R

vars <- c("mpg", "hp", "wt")
head(mtcars[vars])


                   mpg  hp    wt
Mazda RX4         21.0 110 2.620
Mazda RX4 Wag     21.0 110 2.875
Datsun 710        22.8  93 2.320
Hornet 4 Drive    21.4 110 3.215
Hornet Sportabout 18.7 175 3.440
Valiant           18.1 105 3.460


In [4]:
%R summary(mtcars[vars])

array(['Min.   :10.40  ', '1st Qu.:15.43  ', 'Median :19.20  ',
       'Mean   :20.09  ', '3rd Qu.:22.80  ', 'Max.   :33.90  ',
       'Min.   : 52.0  ', '1st Qu.: 96.5  ', 'Median :123.0  ',
       'Mean   :146.7  ', '3rd Qu.:180.0  ', 'Max.   :335.0  ',
       'Min.   :1.513  ', '1st Qu.:2.581  ', 'Median :3.325  ',
       'Mean   :3.217  ', '3rd Qu.:3.610  ', 'Max.   :5.424  '], 
      dtype='|S15')

In [5]:
%%file script/mystats.R

 mystats <- function(x, na.omit=FALSE){
               if (na.omit)
                   x <- x[!is.na(x)]
               m <- mean(x)
               n <- length(x)
               s <- sd(x)
               skew <- sum((x-m)^3/s^3)/n
               kurt <- sum((x-m)^4/s^4)/n - 3
               return(c(n=n, mean=m, stdev=s, skew=skew, kurtosis=kurt))
             }


Overwriting script/mystats.R


In [6]:
%%R
source("script/mystats.R")

sapply(mtcars[vars], mystats)

               mpg          hp          wt
n        32.000000  32.0000000 32.00000000
mean     20.090625 146.6875000  3.21725000
stdev     6.026948  68.5628685  0.97845744
skew      0.610655   0.7260237  0.42314646
kurtosis -0.372766  -0.1355511 -0.02271075


In [7]:
%%R
library(Hmisc)
describe(mtcars[vars])

Loading required package: grid
Loading required package: lattice
Loading required package: survival
Loading required package: splines
Loading required package: Formula

Attaching package: ‘Hmisc’

The following objects are masked from ‘package:base’:

    format.pval, round.POSIXt, trunc.POSIXt, units

mtcars[vars] 

 3  Variables      32  Observations
--------------------------------------------------------------------------------
mpg 
      n missing  unique    Info    Mean     .05     .10     .25     .50     .75 
     32       0      25       1   20.09   12.00   14.34   15.43   19.20   22.80 
    .90     .95 
  30.09   31.30 

lowest : 10.4 13.3 14.3 14.7 15.0, highest: 26.0 27.3 30.4 32.4 33.9 
--------------------------------------------------------------------------------
hp 
      n missing  unique    Info    Mean     .05     .10     .25     .50     .75 
     32       0      22       1   146.7   63.65   66.00   96.50  123.00  180.00 
    .90     .95 
 243.50  253.55 

lowest :  

In [8]:
%%R

library(pastecs)
stat.desc(mtcars[vars])

Loading required package: boot

Attaching package: ‘boot’

The following object is masked from ‘package:survival’:

    aml

The following object is masked from ‘package:lattice’:

    melanoma

                     mpg           hp          wt
nbr.val       32.0000000   32.0000000  32.0000000
nbr.null       0.0000000    0.0000000   0.0000000
nbr.na         0.0000000    0.0000000   0.0000000
min           10.4000000   52.0000000   1.5130000
max           33.9000000  335.0000000   5.4240000
range         23.5000000  283.0000000   3.9110000
sum          642.9000000 4694.0000000 102.9520000
median        19.2000000  123.0000000   3.3250000
mean          20.0906250  146.6875000   3.2172500
SE.mean        1.0654240   12.1203173   0.1729685
CI.mean.0.95   2.1729465   24.7195501   0.3527715
var           36.3241028 4700.8669355   0.9573790
std.dev        6.0269481   68.5628685   0.9784574
coef.var       0.2999881    0.4674077   0.3041285


In [9]:
%%R

library(psych)
describe(mtcars[vars])


Attaching package: ‘psych’

The following object is masked from ‘package:boot’:

    logit

The following object is masked from ‘package:Hmisc’:

    describe

    vars  n   mean    sd median trimmed   mad   min    max  range skew kurtosis
mpg    1 32  20.09  6.03  19.20   19.70  5.41 10.40  33.90  23.50 0.61    -0.37
hp     2 32 146.69 68.56 123.00  141.19 77.10 52.00 335.00 283.00 0.73    -0.14
wt     3 32   3.22  0.98   3.33    3.15  0.77  1.51   5.42   3.91 0.42    -0.02
       se
mpg  1.07
hp  12.12
wt   0.17


In [10]:
%R aggregate(mtcars[vars], by=list(am=mtcars$am), mean)

array([[   0.        ,    1.        ],
       [  17.14736842,   24.39230769],
       [ 160.26315789,  126.84615385],
       [   3.76889474,    2.411     ]])

In [11]:
%R  aggregate(mtcars[vars], by=list(am=mtcars$am), sd)

array([[  0.        ,   1.        ],
       [  3.83396639,   6.16650381],
       [ 53.90819573,  84.06232425],
       [  0.77740015,   0.61698163]])

In [12]:
%%R  
dstats <- function(x)(c(mean=mean(x), sd=sd(x)))
    
by(mtcars[vars], mtcars$am, dstats)

Error in is.data.frame(x) : 
  (list) object cannot be coerced to type 'double'
In addition: Warning message:
In mean.default(x) : argument is not numeric or logical: returning NA
Error in is.data.frame(x) : 
  (list) object cannot be coerced to type 'double'


In [15]:
%%R

library(doBy)
summaryBy(mpg+hp+wt~am, data=mtcars, FUN=mystats)

  am mpg.n mpg.mean mpg.stdev   mpg.skew mpg.kurtosis hp.n  hp.mean hp.stdev
1  0    19 17.14737  3.833966 0.01395038   -0.8031783   19 160.2632 53.90820
2  1    13 24.39231  6.166504 0.05256118   -1.4553520   13 126.8462 84.06232
      hp.skew hp.kurtosis wt.n  wt.mean  wt.stdev   wt.skew wt.kurtosis
1 -0.01422519  -1.2096973   19 3.768895 0.7774001 0.9759294   0.1415676
2  1.35988586   0.5634635   13 2.411000 0.6169816 0.2103128  -1.1737358


In [16]:
%%R
 library(psych)
 describe.by(mtcars[vars], mtcars$am)

group: 0
    vars  n   mean    sd median trimmed   mad   min    max  range  skew
mpg    1 19  17.15  3.83  17.30   17.12  3.11 10.40  24.40  14.00  0.01
hp     2 19 160.26 53.91 175.00  161.06 77.10 62.00 245.00 183.00 -0.01
wt     3 19   3.77  0.78   3.52    3.75  0.45  2.46   5.42   2.96  0.98
    kurtosis    se
mpg    -0.80  0.88
hp     -1.21 12.37
wt      0.14  0.18
------------------------------------------------------------ 
group: 1
    vars  n   mean    sd median trimmed   mad   min    max  range skew kurtosis
mpg    1 13  24.39  6.17  22.80   24.38  6.67 15.00  33.90  18.90 0.05    -1.46
hp     2 13 126.85 84.06 109.00  114.73 63.75 52.00 335.00 283.00 1.36     0.56
wt     3 13   2.41  0.62   2.32    2.39  0.68  1.51   3.57   2.06 0.21    -1.17
       se
mpg  1.71
hp  23.31
wt   0.17


In [17]:
%%R

library(reshape)
dstats <- function(x)(c(n=length(x), mean=mean(x), sd=sd(x)))
dfm <- melt(mtcars, measure.vars=c("mpg", "hp", "wt"), 
            id.vars=c("am", "cyl"))
cast(dfm, am + cyl + variable ~ ., dstats)

   am cyl variable  n       mean         sd
1   0   4      mpg  3  22.900000  1.4525839
2   0   4       hp  3  84.666667 19.6553640
3   0   4       wt  3   2.935000  0.4075230
4   0   6      mpg  4  19.125000  1.6317169
5   0   6       hp  4 115.250000  9.1787799
6   0   6       wt  4   3.388750  0.1162164
7   0   8      mpg 12  15.050000  2.7743959
8   0   8       hp 12 194.166667 33.3598379
9   0   8       wt 12   4.104083  0.7683069
10  1   4      mpg  8  28.075000  4.4838599
11  1   4       hp  8  81.875000 22.6554156
12  1   4       wt  8   2.042250  0.4093485
13  1   6      mpg  3  20.566667  0.7505553
14  1   6       hp  3 131.666667 37.5277675
15  1   6       wt  3   2.755000  0.1281601
16  1   8      mpg  2  15.400000  0.5656854
17  1   8       hp  2 299.500000 50.2045815
18  1   8       wt  2   3.370000  0.2828427


#Frequency and contingency tables
In  this section, we’ll  look at  frequency and contingency  tables  from categorical vari-
ables,  along with  tests  of  independence, measures  of  association,  and methods  for
graphically displaying results. We’ll be using functions in the basic installation, along
with functions from the vcd and gmodels package. In the following examples, assume
that A, B, and C represent categorical variables.
The data for this section come from the Arthritis dataset included with the vcd
package. The data are  from Kock & Edward (1988) and  represent a double-blind clinical
trial of new treatments for rheumatoid arthritis. Here are the first few observations:

In [19]:
%%R

library(vcd)
head(Arthritis)

  ID Treatment  Sex Age Improved
1 57   Treated Male  27     Some
2 46   Treated Male  29     None
3 77   Treated Male  30     None
4 17   Treated Male  32   Marked
5 36   Treated Male  46   Marked
6 23   Treated Male  58   Marked


In [20]:
%%R

mytable <- with(Arthritis, table(Improved))
mytable

Improved
  None   Some Marked 
    42     14     28 


In [22]:
%R prop.table(mytable)

array([ 0.5       ,  0.16666667,  0.33333333])